### ISSUE TITLE
Загрузка процессора 100%

### ISSUE THREAD

**Issue by shojkeee** [ntguest/32bit-home-assistant-supervised-installer#2]
Привет. Спасибо за Ваш opiz2.sh скрипт. Он рабочий и меня выручил. Надеюсь вы его не будете отсюда удалять. Так как планирую его использовать в дальнейшем. 

Но столкнулся с проблемой. У меня Orangepizero2 и если брать Вашу записку https://github.com/ntguest/32bit-home-assistant-supervised-installer/blob/main/files/opizero2

то после установки докера процессор "кушает" на 100% этот докер и orpz2 начинает греться до 80 градусов и выше. Что не есть хорошо.
![image](https://user-images.githubusercontent.com/72029085/154498791-9666dfb5-f748-411b-9cdb-f02f8f2369ab.png)

Я парился долго по этому поводу и прешел к выводу, что проблема именно в докере с репозитория который указан в Вашей записке.

Если установить его с репозитория:
sudo add-apt-repository universe

и установить докер:
sudo apt-get -y install avahi-daemon jq docker.io

то процессор не будет так загружен и вполне себе orangepizero2 потянет home assistant supervisor у меня работает и температура держится в пределе 50 градусов:
![image](https://user-images.githubusercontent.com/72029085/154497455-90a3a7ec-f9fb-4e72-8e5f-fc024de60332.png)

Но конечно так просто репозиторий universe не встанет. Эти дебильные образы armbian все куцые и нормально работающего образа просто нет. А для добавления репозитория universe нужен linux 5.13. Armbian образы рабочие только до 4.9

Вобщем надо брать образ с сайте orange pi. Там у них декабрьский образ есть убунты какраз на линуксе 5.13

https://drive.google.com/drive/folders/13pY93TozoF2omgKYnCiSZrONbBvBPxAh

Надеюсь эта информация будет полезна.

P.S. спасибо еще раз за скрипт)

**Comment by ntguest** [comment]
загрузка процессора описана [здесь ](https://github.com/home-assistant/plugin-audio/issues/12) и существует [аддон](https://github.com/OPHoperHPO/hassio-addons/tree/master/pulseaudio_fix) который "решает" проблему.
поэтому я и добавил [бекап ](https://drive.google.com/u/0/uc?id=1IglrNZDfzkpJC0nEDe-7-ibA2CuYV6At&export=download)с уже установленными исправлениями не вдаваясь детали.

**Comment by ntguest** [comment]
убедительная просьба в видео и на сайте поставить на самое видное место ссыль для подаяния автору инструкции и скрипта https://yoomoney.ru/to/410011383527168
