### ISSUE TITLE
Runing the program

### ISSUE THREAD

**Issue by FranciscoMaioR** [ntguest/32bit-home-assistant-supervised-installer#3]
After completing the tutorial how do I run the program?
edit: Im using a 32 bit computer

**Comment by ntguest** [comment]
keep calm and wait while system will be available at installer hint url

**Comment by FranciscoMaioR** [comment]
Im sorry but I'm really new at this, what is the "installer hint URL"? is there a set of commands you can tell me to run HA? after the reboot I log in and nothing happens

**Comment by ntguest** [comment]
When you passes all steps without any errors you can see message:
----------------------------------------------------------------------
Home Assistant supervised is now installed
First setup will take some time, when it's ready you can reach it here:
http://{YOUR_IP_ADDRESS}:8123

Don't forget visit https://www.buymeacoffee.com/ntguest
------------------------------------------------------------------------
here is 
just wait 20-30... minutes
